name: Push-FinalRepoExam-to-Ec2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            : ${VERSION:=1}
            cd home
            sudo rm -rf project
            sudo mkdir -p project/clcm3504-finalexam-folder
            sudo mv docker-compose.yml project
            sudo mv README.md project/clcm3504-finalexam-folder
            cd project
            sudo yum -y update
            sudo yum install -y docker
            sudo systemctl start docker
            sudo yum install docker-compose-plugin
            sudo docker login -u="gerardo0579bvc" -p=${{ secrets.DOCKER_PASS }} docker.io
            sudo echo -e "FROM httpd:2.4\nCOPY ./clcm3504-finalexam-folder/ " | sudo tee Dockerfile
            sudo docker-compose up -d
            sudo docker tag "$(sudo docker images -q clcm3504-finalexam-image)" gerardo0579bvc/clcm3504-finalexam-image:v$VERSION
            sudo docker push gerardo0579bvc/clcm3504-finalexam-image:v$VERSION
            cd /home
            export VERSION=$((VERSION + 1))
            
